apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: cleanupdisk
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
spec:
  schedule: "0 10 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: cleanupdisk
        spec:
          serviceAccountName: {{ template "fullname" . }}
          restartPolicy: Never
          containers:
          - image: softonic/kube-gcp-disks-roomba:{{ .Values.image.tag }}
            args:
	    {{- range .Values.args }}
            - {{ . }}
            {{- end }}
            name: cleanupdisk
            volumeMounts:
            - name: credentials
              mountPath: /secrets
            env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /secrets/credentials.json
          imagePullSecrets:
          - name: registry.softonic.one
          volumes:
          - name: credentials
            secret:
              secretName: credentials
